[project]
name = "03-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.14.2",
    "minsearch>=0.0.7",
    "requests>=2.32.5",
]
